name       : libdigidoc
version    : 3.10.5
release    : 2
source     :
    - https://github.com/open-eid/libdigidoc/releases/download/v3.10.5/libdigidoc-3.10.5.tar.gz : f635bbce14936b5a7d1eeac9623874ba56982c15b07c2ccd3f9865138932835b
license    : LGPL-2.1-or-later
component  : programming.library
summary    : DigiDoc is an XML file format for documents with digital signatures in use by the Estonian ID card infrastructure. This library allows for creation and reading of DigiDoc files.
description: |
    DigiDoc is an XML file format for documents with digital signatures in use by the Estonian ID card infrastructure. This library allows for creation and reading of DigiDoc files.
builddeps  :
    - pkgconfig(p11-kit-1)
    - libiconv-devel
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
