name       : libdigidoc
version    : 3.10.3
release    : 1
source     :
    - git|https://github.com/open-eid/libdigidoc : v3.10.3
license    : LGPL-2.1
component  : programming.library
summary    : DigiDoc is an XML file format for documents with digital signatures in use by the Estonian ID card infrastructure. This library allows for creation and reading of DigiDoc files.
description: |
    DigiDoc is an XML file format for documents with digital signatures in use by the Estonian ID card infrastructure. This library allows for creation and reading of DigiDoc files.
builddeps  :
    - pkgconfig(p11-kit-1)
    - libiconv-devel
    - doxygen
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
